services:
  # Servidor NATS
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"

  # Configuraci贸n de MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Configuraci贸n de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
    # Configuraci贸n de postgres
  postgres:
    image: postgres:16.2
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgre
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

    # Configuraci贸n de Redis
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data



  api-gateway:
    build: ./api-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
      - ${CLIENT_SOCKET_PORT}:3001
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - SOCKET_PORT=3001
      - NAST_SERVERS=nats://nats-server:4222

  auth-ms:
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    depends_on:
      - nats-server
    command: npm run start:dev
    environment:
      - PORT=3000
      - NAST_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${MONGO_URI}/AuthDb #mongodb://root:example@mongodb:27017/AuthDb
      - JWT_SECRET=estoDeberiaSerUnStringSeguro


  notification-ms:
    build: ./notification-ms
    volumes:
      - ./notification-ms/src:/usr/src/app/src
    depends_on:
      - nats-server
    command: npm run start:dev
    environment:
      - PORT=3000
      - NAST_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${MONGO_URI}/Notifications


  assets-ms:
    build: ./assets-ms
    volumes:
      - ./assets-ms/src:/usr/src/app/src
    depends_on:
      - nats-server
    command: npm run start:dev
    environment:
      - PORT=3000
      - NAST_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/postgres


volumes:
  mongo_data:
  mysql_data:
  postgres_data:
  redis_data: