version: '3'
services:
  # Servidor NATS
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"

  # Configuración de MongoDB
  mongodb:
    image: mongo:6.0
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    
    # Configuración de postgres
  postgres:
    image: postgres:16.2
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgre
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

    # Configuración de Redis
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data



  api-gateway:
    build: ./api-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
      - ${CLIENT_SOCKET_PORT}:3001
    volumes:
      - ./api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - SOCKET_PORT=3001
      - NAST_SERVERS=nats://nats-server:4222
      - REDIS_CLIENT=redis://redis_container:6379

  auth-ms:
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    depends_on:
      - nats-server
    command: npm run start:dev
    environment:
      - PORT=3000
      - NAST_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${MONGO_URI_AUTH}
      - JWT_SECRET=estoDeberiaSerUnStringSeguro


  notification-ms:
    build: ./notification-ms
    volumes:
      - ./notification-ms/src:/usr/src/app/src
    depends_on:
      - nats-server
    command: npm run start:dev
    environment:
      - PORT=3000
      - NAST_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${MONGO_URI_NOTIFICATIONS}


  assets-ms:
    build: ./assets-ms
    volumes:
      - ./assets-ms/src:/usr/src/app/src
    depends_on:
      - nats-server
    command: npm run start:dev
    environment:
      - PORT=3000
      - NAST_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgres://postgres:123456@postgres:5432/postgres


volumes:
  mongo_data:
  postgres_data:
  redis_data: